name: Build Windows App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Navigate to project directory
      - name: Change to Project Directory
        run: cd project-directory

      # Step 3: Set up Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: |
          cd project-directory
          flutter pub get

      # Step 5: Build the Windows app
      - name: Build Windows App
        run: |
          cd project-directory
          flutter build windows

      # Step 6: Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: p2p_file_sharing/build/windows/runner/Release
