name: Build Flutter Windows App

on:
  push:
    branches:
      - master# Change this to your default branch if necessary
  pull_request:
    branches:
      - master  # Optional: run on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'  # Use the required Java version

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/runner/Release/
