name: Build Flutter Windows App

on:
  push:
    branches:
      - master  # Update to match your default branch
  pull_request:
    branches:
      - master  # Run on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Ensure compatibility with your Flutter project

      # Step 3: Install Flutter
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
          flutter doctor -v  # Verify Flutter installation

      # Step 4: Change to the project directory
      - name: Navigate to project directory
        working-directory: p2p_file_sharing/p2p_file_sharing
        run: echo "Moved to project directory"

      # Step 5: Run Flutter Pub Get
      - name: Run Flutter Pub Get
        working-directory: p2p_file_sharing/p2p_file_sharing
        run: flutter pub get

      # Step 6: Build Windows App
      - name: Build Windows App
        working-directory: p2p_file_sharing/p2p_file_sharing
        run: flutter build windows --release

      # Step 7: Archive build artifacts
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: p2p_file_sharing/p2p_file_sharing/build/windows/runner/Release/
