name: Build Flutter Windows App

on:
  push:
    branches:
      - mock-name  # Update to match your default branch
  pull_request:
    branches:
      - mocka-name  # Run on pull requests to the main branch. Not using real branch names because I'm not yet ready for it :)

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Ensure compatibility with your Flutter project

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
          flutter doctor -v  # Verify Flutter installation

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/
