name: Build Windows App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Dependencies for Windows
      - name: Install Dependencies for Windows
        run: choco install visualstudio2019buildtools -y

      # Step 3: Set up Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      # Step 4: Navigate to Project Directory and Install Flutter Dependencies
      - name: Install Flutter Dependencies
        working-directory: p2p_file_sharing
        run: flutter pub get

      # Step 5: Build the Windows app
      - name: Build Windows App
        working-directory: p2p_file_sharing
        run: flutter build windows

      # Step 6: Upload the build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: p2p_file_sharing/build/windows/runner/Release
